### ISSUE TITLE
Fork in Golden Set

### ISSUE THREAD

**Issue by nm6061** [RepoReapers/reaper#12]
**Gertjanpfsense/pfsense** [1787241] is a fork of **pfsense/pfsense** [3040416] and the forked repository is in our Golden Set. @craigcabrey and @stevekroh: Do you think we should replace 1787241 with 3040416 and re-compute the attribute thresholds from the Golden Set and the score of the 2m projects in `reaper_results`?

**Comment by nm6061** [comment]
Here are the attribute values for both these projects:

```
Gertjanpfsense/pfsense

    architecture              0.06388888888888888
    community                 5
    continuous_integration    False
    documentation             0.12812189799670795
    history                   6.863636363636363
    license                   True
    management                0.0
    state                     active
    stars                     0
    unit_test                 0

pfsense/pfsense

    architecture              0.06388888888888888
    community                 6
    continuous_integration    False
    documentation             0.12811310403745566
    history                   50.186440677966104
    license                   True
    management                13.389830508474576
    state                     active
    stars                     783
    unit_test                 0
```

The attribute values are not significantly different to have an impact on the currently established thresholds. I am going to replace Gertjanpfsense/pfsense with pfsense/pfsense in our Golden Set.

**Comment by craigcabrey** [comment]
The original intention was for pfsense/pfsense to be in the golden set, so that seems appropriate to me. Not sure how a fork got in there.
