### ISSUE TITLE
Do I need `reaper_results` table in my ghtorrent database to run batch_score.py? What should be the table format and data inside it?

### ISSUE THREAD

**Issue by nasifimtiazohi** [RepoReapers/reaper#16]
I changed the config file and passed the required parameters while running batch_score.py.
The script can make the database connection to my ghtorrent database successfully (I've tested it).
However, It first asked me that it can not find the `reaper_results` table in the database.
Although no mention in the readme file, I still loaded the dataset from https://reporeapers.github.io/ and loaded in the dataset in a table and naming it 'reaper_results'.
However, now it gives an error that it can't find `management` column (the attributes are set in the manifest.json as I understand). The dataset on the website, however, has no `management` column.

The error report I get is,

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/adminuser/Desktop/reaper/lib/database.py", line 43, in get
    cursor.execute(query)
  File "/usr/local/lib/python3.6/site-packages/mysql/connector/cursor.py", line 551, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/local/lib/python3.6/site-packages/mysql/connector/connection.py", line 490, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/usr/local/lib/python3.6/site-packages/mysql/connector/connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.ProgrammingError: 1054 (42S22): Unknown column 'management' in 'field list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/Users/adminuser/Desktop/reaper/lib/run.py", line 59, in _process
    self._save(project_id, rresults, table)
  File "/Users/adminuser/Desktop/reaper/lib/run.py", line 67, in _save
    _rresults = self._get(project_id, table)
  File "/Users/adminuser/Desktop/reaper/lib/run.py", line 133, in _get
    project_id=project_id
  File "/Users/adminuser/Desktop/reaper/lib/database.py", line 57, in get
    raise DatabaseError(msg)
lib.database.DatabaseError: "Failure in executing query SELECT architecture,community,continuous_integration,documentation,history,license,management,project_size,repository_size,state,stars,unit_test FROM reaper_results WHERE project_id = 1. Error: 1054 (42S22): Unknown column 'management' in 'field list'"
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/adminuser/Desktop/reaper/lib/run.py", line 39, in run
    chunksize=1
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 274, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
lib.database.DatabaseError: "Failure in executing query SELECT architecture,community,continuous_integration,documentation,history,license,management,project_size,repository_size,state,stars,unit_test FROM reaper_results WHERE project_id = 1. Error: 1054 (42S22): Unknown column 'management' in 'field list'"
```

I've tried to look at the inner working of the code, but it is probably too big a task. My goal is to get a score for a list of repository so that I can tell if they're actual software development project or not.

Any help?

**Comment by nasifimtiazohi** [comment]
the current `config.json.skel` doesn't contain the option `persist_enabled`.
However, I still put `project_id` and `score` column in the table.

But it seems like somewhere in the code,
it tries to execute the query,
`SELECT architecture,community,continuous_integration,
documentation,history,license,management,project_size,
repository_size,state,stars,unit_test
 FROM reaper_results WHERE project_id = 1`

I assume the columns are chosen from the `manifest.json` file but I don't know how to provide this data.

I have loaded the dataset given in https://reporeapers.github.io/results/1.html in a table named 'reaper_results', with added columns `project_id` and `score`, in case the code wants to write in the table. But while many of the column names in the query is in this dataset, fields like `management, project_size, repo_size` are missing.

I'm not sure how to deal with this issue

**Comment by nuthanmunaiah** [comment]
Yes, `reaper_results` is required to run `batch_score.py` and the `CREATE TABLE` SQL command for it is in the README. As for the data in the table, there is no need to have any data pre-loaded. `batch_score.py` was implemented to update the data if it exists or insert the data if none exists.

Side Note: The `persistResult` key is no longer a part of the `batch_score.py` command line arguments. I will update the README to reflect this soon. However, you can control if the results are persisted or not by using the `--key-string` argument. The `--key-string` argument is parsed such that any upper case attribute initial is treated as an attribute whose result must be persisted. For instance, if you want to collect _only_ documentation and history from a project and persist it to the database, you can use `--key-string=DH`. By default (i.e. if you don't specify a `--key-string`), all enabled attributes are persisted to the database.

**Comment by nasifimtiazohi** [comment]
thanks.
