### ISSUE TITLE
Archictecture: Improve Performance

### ISSUE THREAD

**Issue by nm6061** [RepoReapers/reaper#6]
Modify *architecture* attribute to NOT read and lex source files twice.

**Comment by nm6061** [comment]
@craigcabrey: I have forked the repository to implement this change so that you can review it before it gets into master. I have refactored the code to read and lex source files once. As part of this exercise, I noticed that the call to `ctags` to get the list of files in a particular language is also processor-intensive. Do you think this is a good opportunity to swap out `ctags` with an alternative tool, say `ack` (http://beyondgrep.com/documentation/)?

`ack` is capable of recursively listing all files in a directory that have a specific extension. For instance, to get all C++ files, we could execute `ack -f --cpp repository_path`. It takes 2.6 seconds to discover all C++ files (9895) in the Mongo DB repository, while our approach with `ctags` takes 773.50 seconds to identify 9758 files. Also, the output from `ack -f --cpp repository_path` is a list of absolute paths to the files we need, so we don't have to post process the output. 

`ack` **Output**

```
$ time ack -f --cpp /home/reporeaper/goldenset/repos/284/ | head
/home/reporeaper/goldenset/repos/284/mongodb-mongo-2f62452/src/mongo/base/checked_cast.h
/home/reporeaper/goldenset/repos/284/mongodb-mongo-2f62452/src/mongo/base/compare_numbers.h
/home/reporeaper/goldenset/repos/284/mongodb-mongo-2f62452/src/mongo/base/counter.h
/home/reporeaper/goldenset/repos/284/mongodb-mongo-2f62452/src/mongo/base/counter_test.cpp
/home/reporeaper/goldenset/repos/284/mongodb-mongo-2f62452/src/mongo/base/data_cursor.h
/home/reporeaper/goldenset/repos/284/mongodb-mongo-2f62452/src/mongo/base/data_cursor_test.cpp
/home/reporeaper/goldenset/repos/284/mongodb-mongo-2f62452/src/mongo/base/data_view.h
/home/reporeaper/goldenset/repos/284/mongodb-mongo-2f62452/src/mongo/base/data_view_test.cpp
/home/reporeaper/goldenset/repos/284/mongodb-mongo-2f62452/src/mongo/base/disallow_copying.h
/home/reporeaper/goldenset/repos/284/mongodb-mongo-2f62452/src/mongo/base/encoded_value_storage.h
```

**Comment by craigcabrey** [comment]
Yes, I've heard good things about `ack`. It's probably a good idea just to switch to that tool (even though it does seem to depend on file extensions, but we honestly should be able to trust that -- we can even assert that it's adhering to best practices ;).

**Comment by nm6061** [comment]
Great. I have the change committed on the fork. I'll run a couple of before-after numbers just to make sure that the refactor was indeed a "refactor". If all is well, you should see a pull request from me later this evening.
